/**
 * Types of auditable activity within an organization.
 */
export enum ActivityType {
  MEMBER_JOINED = "MEMBER_JOINED",
  MEMBER_LEFT = "MEMBER_LEFT",
  MEMBER_REMOVED = "MEMBER_REMOVED",
  ROLE_CHANGED = "ROLE_CHANGED",
  DISCUSSION_CREATED = "DISCUSSION_CREATED",
  DISCUSSION_CLOSED = "DISCUSSION_CLOSED",
  ANNOUNCEMENT_PUBLISHED = "ANNOUNCEMENT_PUBLISHED",
  EVENT_SCHEDULED = "EVENT_SCHEDULED",
  EVENT_CANCELLED = "EVENT_CANCELLED",
  DOCUMENT_SHARED = "DOCUMENT_SHARED",
  INVITE_SENT = "INVITE_SENT",
}
