/**
 * Types of audit events
 * recorded by Evantra Identity.
 */
export enum AuditAction {

  ACCOUNT_REGISTERED = "ACCOUNT_REGISTERED",

  ACCOUNT_VERIFIED = "ACCOUNT_VERIFIED",

  LOGIN_SUCCESS = "LOGIN_SUCCESS",

  LOGIN_FAILED = "LOGIN_FAILED",

  PASSWORD_CHANGED = "PASSWORD_CHANGED",

  PASSWORD_RESET = "PASSWORD_RESET",

  CONTACT_EMAIL_CHANGED = "CONTACT_EMAIL_CHANGED",

  CONTACT_EMAIL_VERIFIED = "CONTACT_EMAIL_VERIFIED",

  SESSION_CREATED = "SESSION_CREATED",

  SESSION_REFRESHED = "SESSION_REFRESHED",

  SESSION_ROTATED = "SESSION_ROTATED",

  SESSION_REVOKED = "SESSION_REVOKED",

  ALL_SESSIONS_REVOKED = "ALL_SESSIONS_REVOKED",

}